### ISSUE TITLE
Cant get my playlist to work

### ISSUE THREAD

**Issue by Rainbow-Island** [mirrorfm/mirrorfm-data#68]
Hi

I'm new, and need help with submitting my you tube playlist. 

Anyone who can help it will be very much appreciated.

Thank you :)

**Comment by stephanebruckert** [comment]
I see you have already edited the youtube-channels.csv file here in **your** forked repository, on a branch called patch-3. https://github.com/Rainbow-Island/mirrorfm-data/commits/patch-3  That's perfect, all good so far: people can only edit the file on "their" side before being able to "suggest it" to the main repository (here).

The next step is to create a "pull request" so that your suggested changes are requested. On this page if you click on Pull requests > Create new pull request, you will get here https://github.com/mirrorfm/mirrorfm-data/compare. Then you can choose your forked repository at `Rainbow-Island`, and your branch `patch-3`. At the end you should see https://github.com/mirrorfm/mirrorfm-data/compare/master...Rainbow-Island:mirrorfm-data:patch-3. Then you should see the line you added. You can then just click on "Create pull request"

**Comment by Rainbow-Island** [comment]
Hi
Thanks for your help, I need it!
I cant see anything to click 'Create pull request'
This is where I am:



    On Monday, 11 July 2022 at 23:42:22 BST, Stéphane Bruckert ***@***.***> wrote:  
 
 


I see you have already edited the youtube-channels.csv file here in your forked repository, on a branch called patch-3. https://github.com/Rainbow-Island/mirrorfm-data/commits/patch-3 That's perfect, all good so far: people can only edit the file on "their" side before being able to "suggest it" to the main repository (here).

The next step is to create a "pull request" so that your suggested changes are requested. On this page if you click on Pull requests > Create new pull request, you will get here https://github.com/mirrorfm/mirrorfm-data/compare. Then you can choose your forked repository at Rainbow-Island, and your branch patch-3. At the end you should see master...Rainbow-Island:mirrorfm-data:patch-3. Then you should see the line you added. You can then just click on "Create pull request"

**Comment by stephanebruckert** [comment]
Normally [this link](https://github.com/mirrorfm/mirrorfm-data/compare/master...Rainbow-Island:mirrorfm-data:patch-3) brings you to the "Create pull request" button. 

But I checked your channel and, it doesn't have any videos. It only has a playlist but mirror.fm only handles uploads and not playlists.

**Comment by Rainbow-Island** [comment]
Hi 
oh I thought it was for playlists.
I will try uploading videos when I get the chance.
Thanks will retry everything again asap
regards
Melanie
    On Tuesday, 12 July 2022 at 12:32:26 BST, Stéphane Bruckert ***@***.***> wrote:  
 
 


Normally this link brings you to the "Create pull request" button.

But I checked your channel and, it doesn't have any videos. It only has a playlist but mirror.fm only handles uploads and not playlists.
